# https://github.com/alacritty/alacritty-theme
import = [
  # "~/.config/alacritty/themes/themes/cyber_punk_neon.toml"
  # "~/.config/alacritty/themes/themes/dark_pastels.toml"
  # "~/.config/alacritty/themes/themes/dracula_plus.toml"
  # "~/.config/alacritty/themes/themes/dracula.toml"
  "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]

################################################################################
# https://alacritty.org/config-alacritty.html
#

[window]

dimensions = { columns = 120, lines = 45 }

# Opacity
opacity = 0.98  # Default: 1.0

[font]

# Normal font style
normal = { family = "UDEV Gothic NFLG", style = "Bold" }  # Default for Linux/BSD: "monospace", Regular

# Font size in points
size = 16  # Default: 11.25
