# https://github.com/alacritty/alacritty-theme
import = [
  # "~/.config/alacritty/themes/themes/ayu_dark.toml"
  # "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
  "~/.config/alacritty/themes/themes/monokai_charcoal.toml"
]

################################################################################
# https://alacritty.org/config-alacritty.html
#

[window]
padding = { x = 10, y = 10 }
dimensions = { columns = 120, lines = 45 }
opacity = 0.9  # Default: 1.0
blur = true

[font]
normal = { family = "UDEV Gothic NFLG", style = "Bold" }
size = 18
