# https://github.com/alacritty/alacritty-theme
import = [
  # "~/.config/alacritty/themes/themes/ayu_dark.toml"
  # "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
  "~/.config/alacritty/themes/themes/monokai_charcoal.toml"
]

################################################################################
# https://alacritty.org/config-alacritty.html
#

[window]

dimensions = { columns = 120, lines = 45 }

# Opacity
opacity = 0.95  # Default: 1.0

[font]

# Normal font style
normal = { family = "UDEV Gothic NFLG", style = "Bold" }  # Default for Linux/BSD: "monospace", Regular

# Font size in points
size = 16  # Default: 11.25
