# https://github.com/alacritty/alacritty-theme
general.import = [
  "~/.config/alacritty/themes/themes/Cobalt2.toml"
  # "~/.config/alacritty/themes/themes/monokai_charcoal.toml"
  # "~/.config/alacritty/themes/themes/nightfox.toml"
  # "~/.config/alacritty/themes/themes/thelovelace.toml"
]

################################################################################
# https://alacritty.org/config-alacritty.html
#

[window]
padding = { x = 10, y = 10 }
dimensions = { columns = 140, lines = 45 }
opacity = 1.0  # Default: 1.0
blur = true

[font]
normal = { family = "UDEV Gothic NF", style = "Regular" }
size = 20
